resources:
  - name: my_docker_repo
    type: GitRepo
    configuration: 
      path: ajit-jain/docker-demo
      gitProvider: myGit

pipelines:
  - name: my_demo_pipeline
    steps: 
      - name: bash_demo
        type: Bash
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - echo "$(printenv)"
            - cd ajit-jain/docker-demo
            - ls
        configuration: 
          inputResources: 
            - name: my_docker_repo
          integrations: 
            - name: docker_hub
          
