resources:
  - name: my_docker_repo
    type: GitRepo
    configuration: 
      path: ajit-jain/docker-demo
      gitProvider: myGit

pipelines:
  - name: my_demo_pipeline
    steps: 
      - name: bash_demo
        type: Bash
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - echo "$(printenv)"
            - pushd $res_my_docker_repo_resourcePath
            - ls
            - docker build --tag node-docker:1.0.$run_number . 
            - docker tag node-docker:1.0.$run_number ajitjfrog/testapps123:1.0.$run_number
            - docker push ajitjfrog/testapps123:1.0.$run_number
            - popd
        configuration: 
          inputResources: 
            - name: my_docker_repo
          integrations: 
            - name: docker_hub
          
